### ISSUE TITLE
Game crash when loading save

### ISSUE THREAD

**Issue by bmaupin** [bmaupin/micro-beyond-earth#7]
I created a test save game with Micro Beyond Earth v7. The save loads fine the first time, but the second time I load it, the game crashes.

To do:

- [x] Comment out all mod code to see if it's related to mod functionality
- [x] Load the save without other mods
- [x] Check logs
  - [x] Lua logs: nothing there
  - [x] Other logs
- [x] Do a back trace
- [x] Is it related to the map? no
  - [x] Create a new test save with the same map and try again
  - [x] Different map
- [ ] Related to loading save games in general?
  - [x] Test loading a save game x2 without any mods
  - [x] Test loading save game x2 without mods, a few dozen turns into game
  - [ ] Test a save game x2 with a minimal mod
- [ ] Related to MinCompatibleSaveVersion?
- [x] Related to having two versions of mod installed at once? no
- [ ] Related to map size? Seems to be most likely cause right now ... as best as I can tell it only happens with modded duel maps
  - [x] Test minimal duel map, no special options checked
  - [x] Test minimal dwarf map
  - [ ] Test unmodded duel map (just in case)
  - [ ] Slowly decrease dwarf map size until we find the line where the crashes happen (NOTE: no odd map sizes as per readme)
    - [x] 16x10 (current dwarf size): good
    - [x] 16x8: good
    - [x] 14x10: crash
    - [x] 14x8: crash
    - [x] 12x10: crash
    - [x] 12x8 (current duel size): crash
- [ ] Re-test smallest viable map size several games to be sure

**Comment by bmaupin** [comment]
Seems like some kind of serialisation (or deserialisation) error?

Backtrace:

```
Terminating due to uncaught exception 0x6418c6c0 'std::exception' of type std::exception

Thread 13 "CivBE" received signal SIGABRT, Aborted.
[Switching to Thread 0xe4affac0 (LWP 220530)]
0xf7fc4579 in __kernel_vsyscall ()
(gdb) bt
#0  0xf7fc4579 in __kernel_vsyscall ()
#1  0xf764aaa7 in ?? () from /lib/i386-linux-gnu/libc.so.6
#2  0xf75f9685 in raise () from /lib/i386-linux-gnu/libc.so.6
#3  0xf75e23ac in abort () from /lib/i386-linux-gnu/libc.so.6
#4  0xf77fd117 in std::terminate() () from ./libcxxrt.so
#5  0xf77fdd16 in report_failure(_Unwind_Reason_Code, __cxxabiv1::__cxa_exception*) ()
   from ./libcxxrt.so
#6  0xf77fd667 in throw_exception(__cxxabiv1::__cxa_exception*) () from ./libcxxrt.so
#7  0xf77fd564 in __cxa_throw () from ./libcxxrt.so
#8  0x09147b07 in FDataStream::RaiseException(std::exception&) const ()
#9  0x0916d410 in FMemoryStream::ReadIt(unsigned int, void*) ()
#10 0x08ca1b55 in CvZLibStream::ReadIt(unsigned int, void*) ()
#11 0x09148bd4 in FDataStream::Read(bool&) ()
#12 0xb38e62da in operator>><bool> (stream=..., value=<optimized out>, stream=..., 
    value=<optimized out>) at ../../../Fireplace/Fireworks/FDataStream.h:265
#13 SerializeToSequenceContainer<bool, std::__1::vector<bool, std::__1::allocator<bool> > > (
    loadFrom=..., container=...) at ../../../Fireplace/FireWorks/FStlContainerSerialization.h:115
#14 0xb3a4332f in operator>><bool> (loadFrom=..., writeTo=..., loadFrom=..., writeTo=...)
    at ../../../Fireplace/FireWorks/FStlContainerSerialization.h:263
#15 operator>> (loadFrom=..., writeTo=...)
    at ../../../Civ5/Src/App/CvGameCoreDLL_Expansion1/CvGame.cpp:11246
#16 0xb3a43268 in CvGame::Read (this=0xb429d1d0, kStream=...)
    at ../../../Civ5/Src/App/CvGameCoreDLL_Expansion1/CvGame.cpp:9066
#17 0xb39f8fa9 in CvDllGame::Read (this=0xb92f0410, kStream=...)
    at ../../../Civ5/Src/App/CvGameCoreDLL_Expansion1/CvDllGame.cpp:516
#18 0x08ca5834 in CvGameCoreSerializer::Read(FDataStream&) ()
#19 0x08ca5466 in cvSerializer::ReadObjects(FDataStream&) ()
#20 0x08ca4ebe in cvSerializer::DoLoad(FDataStream&) ()
#21 0x08d381e3 in NetLoadGame::Execute(FNetSessionIFace*) const ()
#22 0x0910b2fd in FNetMessage::Process(FNetSessionIFace*) const ()
#23 0x08adaa74 in NetProxy::HandleMessage(FNetMessage&) ()
#24 0x08ae3abf in NetProxySessionCallbacks::MessageReceived(FNetMessage&) ()
#25 0x09131ece in FNetSession::HandleMessage(FNetMessage&) ()
#26 0x09131d6c in FNetSession::MessageReceived(FNetMessage&, bool) ()
#27 0x09140212 in FNetCallbacksENet::MessageReceived(long, unsigned char const*, unsigned int, bool) ()
#28 0x09128665 in FNetAccessENet::Update() ()
#29 0x09132157 in FNetSession::ProcessNetwork() ()
#30 0x0912aed3 in FNetMessageSync::Update(float) ()
#31 0x0912f039 in FNetSession::Update(float) ()
#32 0x08ad7091 in NetProxy::Update(float) ()
#33 0x08ca23a2 in cvSerializer::LoadGame(cvPath const&, bool) ()
#34 0x08aace1a in InterfaceBuddy::OnPlayerChoseToLoadGame(Events::EventTemplate<Events::Int2Type<154>, LoadGameData, Events::LinearEventDispatcher, LocalMachineContainer, Events::NullEventClass, Events::BaseEvent<cvEventSystemLocalMachineAccessor, cvSubscriptionValidator>, Events::NullEventClass>&) ()
#35 0x08baef9e in Events::LinearEventDispatcher<LocalMachineContainer<Events::EventSubscription<fastdelegate::FastDelegate1<Events::EventTemplate<Events::Int2Type<154>, LoadGameData, Events::LinearEventDispatcher, LocalMachineContainer, Events::NullEventClass, Events::BaseEvent<cvEventSystemLocalMachineAccessor, cvSubscriptionValidator>, Events::NullEventClass>&, void>, Events::NullEventClass> >, Events::EventTemplate<Events::Int2Type<154>, LoadGameData, Events::LinearEventDispatcher, LocalMachineContainer, Events::NullEventClass, Events::BaseEvent<cvEventSystemLocalMachineAccessor, cvSubscriptionValidator>, Events::NullEventClass> >::DispatchEvent(unsigned char*, Events::DispatchData*) ()
...
```

**Comment by bmaupin** [comment]
Most recent logs

stopwatch.log

```
[112.299] , (Lua) CanLoadSavedGame, 0.000243
[112.300] , (Lua) GetSavedGameRequirements, 0.000114
```

Localization.log

```
[58.074] WRN: A resource bundle lookup returned a result from the root locale (not an error).
[90.635] ERR: Missing argument 1. ({1_Num} {1_Num: plural 1?turn; other?turns;} until new citizen)
[90.635] ERR: Failed to evaluate parameter 1. {1_Num} {1_Num: plural 1?turn; other?turns;} until new citizen
[90.636] ERR: Missing argument 1. ({1_Citizen: plural 1?citizen; other?citizens;})
[90.636] ERR: Failed to evaluate parameter 1. {1_Citizen: plural 1?citizen; other?citizens;}
[90.636] ERR: Missing argument 1. ({1_Num} {1_Num: plural 1?turn; other?turns;} until)
[90.636] ERR: Failed to evaluate parameter 1. {1_Num} {1_Num: plural 1?turn; other?turns;} until
[90.643] ERR: Missing argument 1. ({1_NumTurns:number} {1_NumTurns: plural 1?turn; other?turns;} until Border Growth)
[90.643] ERR: Failed to evaluate parameter 1. {1_NumTurns:number} {1_NumTurns: plural 1?turn; other?turns;} until Border Growth
[92.049] ERR: Missing argument 1. (Has made the following {1_Num : plural 1?agreement; other?agreements;}:)
[92.049] ERR: Failed to evaluate parameter 1. Has made the following {1_Num : plural 1?agreement; other?agreements;}:
```

**Comment by bmaupin** [comment]
Here's what I'm seeing so far:

- Seems to crash when loading a save game, but only the second time
- Crash seems to happen starting with map width less than 16 (16x10 is fine, 16x8 is fine?)
- Crash may happen from turn 0 or may not happen until later
  - Having at least one automated worker may or may not be related to the crash

**Comment by bmaupin** [comment]
It's happening again, with a specific duel save created with v10 ...

**Comment by bmaupin** [comment]
I ran into this again on a small map. Seems like the Marvels might have been messed up. I turned off marvels and tested with a 12x8 map and it still crashed on reload, so while it could be related to marvels, that's not the only issue. I'll leave the map sizes as-is.
